### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by raymanyoung** [davis-ramsey/pools-vision#2]
./src/components/UserInput.js
Module not found: Can't resolve './helpers/keys' in 'D:\work\blockchain\pools-vision\src\components'

**Comment by davis-ramsey** [comment]
create a file called keys.js in helpers folder and put this in it

export const infura = '
https://mainnet.infura.io/v3/9fae5b9115104b5da6eabf0294102584';

**Comment by raymanyoung** [comment]
got it

**Comment by raymanyoung** [comment]
it seems to be your infura private key. maybe remove the real key part? @davis-ramsey

**Comment by riordant** [comment]
https://github.com/davis-ramsey/pools-vision/pull/4

Also @davis-ramsey you should delete that comment, you can still see the key in the edits.
